<?php

namespace ContainerJ0CeUEf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6Mpifi4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6Mpifi4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6Mpifi4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AjoutArticleController::addArticle' => ['privates', '.service_locator._yFlKf.', 'get_ServiceLocator_YFlKf_Service', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticlesController::deleteArticle' => ['privates', '.service_locator.NcUNQMU', 'get_ServiceLocator_NcUNQMUService', true],
            'App\\Controller\\ArticlesController::showArticles' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AjoutArticleController:addArticle' => ['privates', '.service_locator._yFlKf.', 'get_ServiceLocator_YFlKf_Service', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'App\\Controller\\ArticlesController:deleteArticle' => ['privates', '.service_locator.NcUNQMU', 'get_ServiceLocator_NcUNQMUService', true],
            'App\\Controller\\ArticlesController:showArticles' => ['privates', '.service_locator.ys8EL7c', 'get_ServiceLocator_Ys8EL7cService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AjoutArticleController::addArticle' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticlesController::deleteArticle' => '?',
            'App\\Controller\\ArticlesController::showArticles' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AjoutArticleController:addArticle' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticlesController:deleteArticle' => '?',
            'App\\Controller\\ArticlesController:showArticles' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
