<?php

namespace ContainerJ0CeUEf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YFlKf_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._yFlKf.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._yFlKf.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'request' => ['privates', '.errored..service_locator._yFlKf..Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator._yFlKf.": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
