<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFT5vEUi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFT5vEUi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFT5vEUi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFT5vEUi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFT5vEUi\App_KernelDevDebugContainer([
    'container.build_hash' => 'FT5vEUi',
    'container.build_id' => '3fa30a50',
    'container.build_time' => 1683841055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFT5vEUi');
