<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIOKUR9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIOKUR9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIOKUR9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIOKUR9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIOKUR9\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIOKUR9',
    'container.build_id' => '07cdc360',
    'container.build_time' => 1683841709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIOKUR9');
