<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV3vAdbg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV3vAdbg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV3vAdbg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV3vAdbg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV3vAdbg\App_KernelDevDebugContainer([
    'container.build_hash' => 'V3vAdbg',
    'container.build_id' => 'cc935c60',
    'container.build_time' => 1640307800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV3vAdbg');
