<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'ajout_article' => [[], ['_controller' => 'App\\Controller\\AjoutArticleController::index'], [], [['text', '/articles/add']], [], []],
    'article' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/articles']], [], []],
    'articles_show_all' => [[], ['_controller' => 'App\\Controller\\ArticlesController::showArticles'], [], [['text', '/articles']], [], []],
    'app_articles_deletearticle' => [['id'], ['_controller' => 'App\\Controller\\ArticlesController::deleteArticle'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/articles/delete']], [], []],
    'app_articles_addarticle' => [['designation', 'description', 'prix'], ['_controller' => 'App\\Controller\\ArticlesController::addArticle'], [], [['variable', '=', '[^/]++', 'prix', true], ['text', '&prix'], ['variable', '=', '[^/]+', 'description', true], ['text', '&description'], ['variable', '=', '[^/]+', 'designation', true], ['text', '/articles/add?designateur']], [], []],
    'app_home_index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'app_lucky_number' => [['max'], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['variable', '/', '[^/]++', 'max', true], ['text', '/lucky/number']], [], []],
    'app_lucky_index' => [[], ['_controller' => 'App\\Controller\\LuckyController::index'], [], [['text', '/index']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/articles']], [], []],
];
